### ISSUE TITLE
Copy Values?

### ISSUE THREAD

**Issue by GavanWilhite** [adamlwgriffiths/Pyrr#100]
What is the recommended way to 'Pass by Value' or copy value from one Vector3 to another?

**Comment by adamlwgriffiths** [comment]
Same as any numpy array

```
>>> import numpy as np
>>> a = np.arange(3)
>>> b = np.arange(3)
>>> a[:] = [1,2,3]
>>> b[:] = a
>>> b
array([1, 2, 3])
```

**Comment by GavanWilhite** [comment]
Ah, it looks like there is actually a copy constructor?

a = Vector3()
b = Vector3(a)

?

**Comment by adamlwgriffiths** [comment]
What do the contents of b look like once you've done that?
