### ISSUE TITLE
Error loading the module into the PyCharm virtual environment

### ISSUE THREAD

**Issue by Alex-zlat** [adamlwgriffiths/Pyrr#121]
When I load the module into the virtual environment of the project on PyCharm, I get the error: 

> SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xea in position 0: invalid continuation byte (sitecustomize.py , line 7)

How to fix the error?

**Comment by adamlwgriffiths** [comment]
Did you look in sitecustomize.py?
That has nothing to do with this library.
Suggest asking on stackoverflow.
