### ISSUE TITLE
No module named multipledispatch

### ISSUE THREAD

**Issue by Tcll** [adamlwgriffiths/Pyrr#26]
download the tar.gz and copy pyrr/ into your local program's directory

    >>> import pyrr
    
    Traceback (most recent call last):
      File "<pyshell#0>", line 1, in <module>
        import pyrr
      File "C:\python27\lib\site-packages\pyrr\__init__.py", line 57, in <module>
        from .objects import (
      File "C:\python27\lib\site-packages\pyrr\objects\__init__.py", line 13, in <module>
        from . import (
      File "C:\python27\lib\site-packages\pyrr\objects\matrix33.py", line 62, in <module>
        from multipledispatch import dispatch
    ImportError: No module named multipledispatch

EDIT:
yes you see site-packages in my directory...
I'm using IDLE through wine, but I've still done the portable installation mentioned above.

**Comment by Permafacture** [comment]
pip install multipledispatch

Why are you using IDLE through wine!?  Native linux is so much easier for programming.  I feel sorry for windows programmers.  If you want to ensure windows compatability, test in a windows VM or on a windows machine.

**Comment by adamlwgriffiths** [comment]
You'll need to install the dependencies.
numpy and multipledispatch

```
pip install numpy multipledispatch
```

or use the requirements file

```
pip install -r requirements.txt
```

**Comment by Tcll** [comment]
> Why are you using IDLE through wine!? Native linux is so much easier for programming. I feel sorry for windows programmers. If you want to ensure windows compatability, test in a windows VM or on a windows machine.

<<<
because my program has it's own integrated portable interpreter so:
- users don't have to download a bunch of pre-requisites (which is VERY annoying)
- I can modify what's installed to work better for my particular interpreter

keep in mind, the only portable interpreter is for windows which is 1 reason I use wine...
another reason I use wine is because linux IDLE doesn't entirely function like windows IDLE...

I forget what exactly doesn't function like I'm used to, but I like windows IDLE better :)
it was either using the MMB to scroll, or something with copy/paste... I forget which

so anyways, I need to install multipledispatch (copy and paste in my program's extensions directory)
might want to mark that along-side the dependencies instead of JUST numpy ;)

**Comment by Permafacture** [comment]
By portable interpreter, do you mean an exe that runs on all windows
machines (rather than having to install python)?

By modify what's installed, do you mean copy and paste libraries into your
program's extensions directory?

How do you deal with modules that need to be compiled, like numpy? Do you
need different versions for different windows versions?

Sorry, this is interesting because I've never heard of it.  I'm used to
virtualenvs, where pip installs into my project's directory as I develop,
and then creates a requirements.txt so someone on another computer can `pip
install -r requirements.txt` to install on their system.

**Comment by Tcll** [comment]
> By portable interpreter, do you mean an exe that runs on all windows
machines (rather than having to install python)?

yes, exactly :)
portable as in something you can run off a USB drive

> By modify what's installed, do you mean copy and paste libraries into your
program's extensions directory?

no, by that I mean making modifications to a library...
portable python is 2.7, so thus I can make an extension perform better by removing py3x testing.

> How do you deal with modules that need to be compiled, like numpy? Do you
need different versions for different windows versions?

I prefer the use of egg, whl, or any other portable formats.

considering I'm using py2x (specifically for PyOpenGL as it runs faster), that interpreter I've been told by the python dev-team should be compatible with any version of windows between 95 and 7 (not sure about 8 or 10, but users seem to have no problems)

> Sorry, this is interesting because I've never heard of it

you're fine, I get this alot actually :)

I just hate 3rd-party... :P
I try to keep everything as local as possible, that way I don't have to bloat users with:
- download this
-- this requires that so download that as well
- and download this
-- which requires this
-- and this
error:
-- you didn't download this
-- or this as it wasn't mentioned by an above dependancy

see what I mean by annoying :P
I've ran into this SOOOO many times

I try to include everything needed to get the program running, simply download and run.

for an extension...
if my extension required numpy and you didn't have it, I would include the egg or such as whatever is needed in my extension.
first it would look for numpy in site-packages, next it would check for anything local, and then it would continue using it's included package.

I've fiddled with pip once before...
ended up flipping the table and pulling my hair out because it didn't work properly

I just delete anything that doesn't work now and look for an alternative or attempt to write my own.
here's a few that either wouldn't compile, threw tracebacks over existant un-found modules, or were just plain unfinished:
- PyWin32 (ran once, never found again)
- PyOpenAL (unfinished and wouldn't compile) (working on my own)
- PyGLEW (required by PyGPU) / glewpy (wouldn't compile or not found) (working on my own)
- PyStream (unfinished, docs only mention the shaders themselves, not how to call them)

I've seen just about any form of python extensions which are just plain junk. :P

**Comment by adamlwgriffiths** [comment]
> might want to mark that along-side the dependencies instead of JUST numpy ;)

But it is?

setup.py
```
install_requires = ['numpy', 'multipledispatch'],
```

README.md

> Pyrr requires the following software:
> 
> Python 2.6+ / 3.0+
> NumPy
> multipledispatch

requirements.txt
```
numpy
multipledispatch
```

**Comment by Tcll** [comment]
oh I was meaning here:
https://pypi.python.org/pypi/pyrr/0.6.5

I see it's there now...
it wasn't when I downloaded >_>

I won't question it though... heh

**Comment by adamlwgriffiths** [comment]
Thats for an old version of the library
