### ISSUE TITLE
[request] better comparisons

### ISSUE THREAD

**Issue by Tcll** [adamlwgriffiths/Pyrr#27]
>>> DM=[[1.0,0.0,0.0,0.0], [0.0,1.0,0.0,0.0], [0.0,0.0,1.0,0.0], [0.0,0.0,0.0,1.0]]

native python27:

    >>> defmtx = list(DM)
    >>> tmtx = list(DM)
    >>> if tmtx == defmtx: print True
    
    True

pyrr:

    >>> defmtx = pyrr.Matrix44(DM)
    >>> tmtx = pyrr.Matrix44(DM)
    >>> if (defmtx == tmtx).all(): print True
    
    True

the gripe:

    >>> defmtx == tmtx
    Matrix44([[ True,  True,  True,  True],
           [ True,  True,  True,  True],
           [ True,  True,  True,  True],
           [ True,  True,  True,  True]], dtype=bool)

what's expected:

    >>> defmtx == tmtx
    True

**Comment by adamlwgriffiths** [comment]
The Matrix*, Vector* and Quaternion classes are really numpy arrays with convenience functions.
Although you may expect it, to do this would remove the existing numpy functionality.
You can simply use the .all() logic as you would a normal array.

**Comment by adamlwgriffiths** [comment]
Hmm could add an .all_equal() to the class though.

**Comment by adamlwgriffiths** [comment]
Nm, its the same as .all().

**Comment by Tcll** [comment]
oh so numpy does this too??
I havn't used numpy much, it's only implemented for a few things that use it...

I guess I can make the exception for seamless integration with numpy :)

if you think my code is extremely slow, think again ;)
I don't follow pythonic standards and always stress-test the fastest avalable standards:

object.__class__ is faster than type(object) which is faster than isinstance(object, class)

pythonic standards tell you to use the slowest method.
