### ISSUE TITLE
Quaternions slerp

### ISSUE THREAD

**Issue by bogdanteleaga** [adamlwgriffiths/Pyrr#31]
I may be missing it, but I can't find anything related to quaternion interpolation. I've been reading a bit on it at the moment, this seems slightly interesting.

http://number-none.com/product/Understanding%20Slerp,%20Then%20Not%20Using%20It/

However, any implementation of some sort of interpolation between rotations would be nice.

**Comment by adamlwgriffiths** [comment]
Slerp/Lerp are literally on my TODO list (https://github.com/adamlwgriffiths/Pyrr/blob/master/TODO)

**Comment by bogdanteleaga** [comment]
Ok, sure, I haven't seen that :)
I'll drop the issue. Not sure if I'm gonna use quaternions after all, I'm kinda short on time atm. If I get to implementing it I'll do a PR.

**Comment by adamlwgriffiths** [comment]
Nah, let's leave the issue open, it's an important feature.

**Comment by TaylorMutch** [comment]
Any word on this? Just replaced a camera system with `pyrr` and I really like it. slerp and lerp would be sweet additions.

**Comment by adamlwgriffiths** [comment]
It's definitely needed, but I'm quite busy at the moment.

**Comment by cprogrammer1994** [comment]
I will take a look

**Comment by cprogrammer1994** [comment]
@TaylorMutch  #55 will be ready for merging once tested. I am still searching for examples.

**Comment by adamlwgriffiths** [comment]
Couple of implementations with source
https://keithmaggio.wordpress.com/2011/02/15/math-magician-lerp-slerp-and-nlerp/
https://en.wikipedia.org/wiki/Slerp#Source_Code
http://ggt.sourceforge.net/html/group__Interp.html
http://www.euclideanspace.com/maths/algebra/realNormedAlgebra/quaternions/slerp/index.htm

The Unity API has some interesting functions
http://wiki.etc.cmu.edu/unity3d/index.php/Interpolation_(Lerps,_SLerps,_and_more)

**Comment by adamlwgriffiths** [comment]
Slerp unit tests from GLM [here](https://github.com/g-truc/glm/blob/44a981ea68f4d919ede24e3df3aeb221b6714d5b/test/gtc/gtc_quaternion.cpp#L131)

**Comment by cprogrammer1994** [comment]
Thanks! I implemented those tests.

Are the comments correct [here](https://github.com/g-truc/glm/blob/44a981ea68f4d919ede24e3df3aeb221b6714d5b/test/gtc/gtc_quaternion.cpp#L179)?

**Comment by cprogrammer1994** [comment]
#55

**Comment by adamlwgriffiths** [comment]
Fixed by #55
