### ISSUE TITLE
matrix44.create_from_xyz_rotation ?

### ISSUE THREAD

**Issue by stuaxo** [adamlwgriffiths/Pyrr#32]
Is there any chance of getting create_from_xyz_rotation ?

(I guess the other combinations could be useful too) ?

**Comment by adamlwgriffiths** [comment]
There is a matrix33/44.create_from_eulers, which should take a pitch,roll,yaw rotation (in that order).

**Comment by stuaxo** [comment]
Thanks, I'm not super numeric so wasn't sure if that was the right thing.

**Comment by adamlwgriffiths** [comment]
pitch, roll, yaw, should map to X,Z,Y(? perhaps -Z?) as OpenGL is a right-handed co-ordinate system, the camera looks down -Z.
I've got tests for the functions, so they should work as expected. But I don't use Eulers myself for anything. I much prefer quaternions / matrices.
Feel free to raise an issue if you find anything strange.

**Comment by stuaxo** [comment]
Good points !     I'm coming back to 3D after many years, I'm sure I probably will switch to quaternians.

I'm trying to port a webgl/glm example to pyopengl - just realised the it uses  gl matrix.rotation, which is a little different:

https://code.google.com/p/glmatrix/wiki/Usage

```
mat4.rotate(mat, angle, axis, dest)

Rotates mat by angle (given in radians) around the axis given by the vector axis.
```

Any idea how I can do something similar with pyrr ?

**Comment by adamlwgriffiths** [comment]
Yeah that's not implemented in matrix (feel free if you know the maths).
There is a quaternion equivalent, ```create_from_axis_rotation(axis, theta, dtype=None)```
It's a hack, but you could create a quaternion, then convert to a matrix, then multiply that with the original matrix. =/

**Comment by stuaxo** [comment]
Ah, maybe ... I'm just porting this example, 

https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Creating_3D_objects_using_WebGL

So might have to, as I'm at the point of checking if I can get the same numbers, for the rotation operation.. I'll dive into GLM an see what it's actually doing first I guess..

**Comment by stuaxo** [comment]
Right, will come back to this - the original does have some output if I remove rotation, so at least I have something to compare with.

glm seems to approach this in a way that looks optimal to JS, but not really sure how that could work in a numpy friendly way:
https://github.com/toji/gl-matrix/blob/master/src/gl-matrix/mat4.js#L484

**Comment by chrsbats** [comment]
Doesn't look to hard.  I'll have a crack at it tomorrow.

**Comment by adamlwgriffiths** [comment]
Created new issue for it, #33
