### ISSUE TITLE
Distribute tests

### ISSUE THREAD

**Issue by FRidh** [adamlwgriffiths/Pyrr#36]
Could you include the tests in the releases? Distributions would like to have these in order to test whether their builds are actually working.

**Comment by adamlwgriffiths** [comment]
Interesting, wasn't aware anyone had use for tests inside the distribution.
I'll try and get some time to do this as soon as I can.

**Comment by adamlwgriffiths** [comment]
Tagged and released on pypi as 0.7.1

**Comment by FRidh** [comment]
Great, thanks!
