### ISSUE TITLE
Quaternion.from_matrix give wrong result

### ISSUE THREAD

**Issue by LexSong** [adamlwgriffiths/Pyrr#42]
R = Quaternion([ 0.80087974,  0.03166748,  0.59114721, -0.09018753])
    print R
    print R.matrix33
    print Quaternion.from_matrix( R.matrix33 )

result:

    [ 0.80087974  0.03166748  0.59114721 -0.09018753]
    [[ 0.29908429  0.1573519   0.94116362]
    [-0.05590453 -0.98172676  0.18189902]
    [ 0.95258767 -0.10701845 -0.28482237]]
    [ 0.80087974  0.03166748  0.59114721  0.09018752]

R != Quaternion.from_matrix( R.matrix33 )

**Comment by LexSong** [comment]
also, `Quaternion.from_matrix( R.matrix33 )` and `Quaternion.from_matrix( R.matrix33.T )` give the same result, even though they should be conjugation of each other

**Comment by adamlwgriffiths** [comment]
=/
I'll see if i can take a look

**Comment by adamlwgriffiths** [comment]
Ok, it seems the optimised "alternative method" listed here gives incorrect values
http://www.euclideanspace.com/maths/geometry/rotations/conversions/matrixToQuaternion/index.htm
I've revered to the less optimised version which seems to produce the correct values.

This also flowed into the quaternion -> matrix conversion and prevented tests from showing an issue there. I updated to a different method found here:
http://www.euclideanspace.com/maths/geometry/rotations/conversions/quaternionToMatrix/index.htm

Thank you for pointing out this issue.
With these changes, all tests are passing - including a new test I added for this issue.
I've bumped the version to 0.8.2, but pypi is 500'ing my account/uploads so I can't update pypi yet =/.

**Comment by LexSong** [comment]
That was fast, thanks for your effort :)

**Comment by adamlwgriffiths** [comment]
Package is uploaded now
Pypi... really don't trust it

**Comment by adamlwgriffiths** [comment]
Apologies for having the error in the first place.
It's important to have a maths library that is correct. I find it deeply upsetting when issues like this present themselves.
If you can think of any other equivalency checks to add to mitigate these issues, I'd be deeply grateful.
