### ISSUE TITLE
Quaternion normalize

### ISSUE THREAD

**Issue by cprogrammer1994** [adamlwgriffiths/Pyrr#54]
```python
def normalise(quat):
    """Ensure a quaternion is unit length (length ~= 1.0).

    The quaternion is **not** changed in place.

    :param numpy.array quat: The quaternion to normalise.
    :rtype: numpy.array
    :return: The normalised quaternion(s).
    """
```

Should the name be normali**z**e?

**Comment by adamlwgriffiths** [comment]
English UK vs English US.
Being from Australia, I use UK English (colour, honour), and most words ending in 'ize' in US are 'ise' in UK english.

Add a `normalize = normalise` below the definition so both are can be used.

**Comment by cprogrammer1994** [comment]
Sorry, my bad. Did not know normalise is valid.

**Comment by adamlwgriffiths** [comment]
All good.
99% of libraries use US English for consistency. It's good to support it.

**Comment by cprogrammer1994** [comment]
would you mind if I change it in #53 this PR? I may rename it to "name-fix" as the original branch is called.

**Comment by adamlwgriffiths** [comment]
I'm not fussed which PR changes go in, as long as the tests pass it's fine.

Assuming the API is still stable we can up the version to `0.9.0` or so and do a release.
If you have a PyPi user, I can give you access to do releases too.

**Comment by cprogrammer1994** [comment]
I add backward compatibility (as far as possible). The tests from the last release will pass too.
