### ISSUE TITLE
generate_normals for vertices instead of faces

### ISSUE THREAD

**Issue by Korijn** [adamlwgriffiths/Pyrr#60]
Your utility `pyrr.vector3.generate_normals` works wonders for generating face normals. However, for constructing vertex normals from those face normals, I needed to write some additional code.

```python
def generate_vertex_normals(vertices, index):
    face_normals = pyrr.vector3.generate_normals(*np.rollaxis(vertices[index], axis=1))
    vertex_normals = np.zeros_like(vertices)
    for i in range(index.shape[-1]):
        np.add.at(vertex_normals, index[:, i], face_normals)
    return pyrr.vector3.normalize(vertex_normals)
```

Is there already such functionality in the library that I may have missed? Is there an intention to add such a utility function?

**Comment by cprogrammer1994** [comment]
Sorry I've read partially the code you wrote.

Is this what you want? (1 -> 2)

![image](https://user-images.githubusercontent.com/11232402/28105266-6f4ece0a-66e7-11e7-87d8-9d53ae8d02b0.png)

**Comment by Korijn** [comment]
Yes, that is correct, going from face normals to vertex normals, basically.

**Comment by cprogrammer1994** [comment]
Sometimes you may need "hints" to get the proper results.

![image](https://user-images.githubusercontent.com/11232402/28106222-a8abee54-66eb-11e7-8a5d-b3bde5db2b64.png)

Most of the modelling programs use smoothing groups to achieve a result like this:

![image](https://user-images.githubusercontent.com/11232402/28105917-5a33a92a-66ea-11e7-95d0-becb1f4f1b3b.png)

However the best examples are terrains. You can achieve the best result if you manually build the normals.

**Comment by Korijn** [comment]
True that! I do think that there are cases where the simple method will suffice, though. :)

**Comment by cprogrammer1994** [comment]
![image](https://user-images.githubusercontent.com/11232402/28106564-f4d4be90-66ec-11e7-94fe-9a62ade145fe.png)

**Comment by Korijn** [comment]
You can easily use the utility function I shared on a smoothing group (subsection of a mesh) too, I think. It doesn't necessarily apply to the whole of a mesh.

**Comment by cprogrammer1994** [comment]
Yes it would be really useful to build /vertex normals for a subset of the faces.

**Comment by Korijn** [comment]
`generate_vertex_normals(vertices, index[smoothing_group])` :)

**Comment by Korijn** [comment]
Alright, I'll open a PR later. :) I'll stick it in `pyrr.vertex3`
