### ISSUE TITLE
Vertex normal for triangle strip

### ISSUE THREAD

**Issue by szabolcsdombi** [adamlwgriffiths/Pyrr#64]
I was wondering if I could generate vertex normals for triangle strips.
Currently `generate_vertex_normals` works fine for indexed triangles but I would like to use this feature on triangle strips.

![image](https://user-images.githubusercontent.com/11232402/28404938-f3526f66-6d33-11e7-92af-75ea850c0856.png)

Generating normals for triangle strips may require support for [Primitive Restart Index](https://www.khronos.org/opengl/wiki/Vertex_Rendering#Primitive_Restart)

Here is an example of a surface using triangle strips and primitive restart index.

```python
for i in range(0, 32):
    for j in range(0, 32):
        vertices.append((i / 32, j / 32, height))

for i in range(0, 32 - 1):
    for j in range(0, 32):
        indices.append(i * 32 + j)
        indices.append((i + 1) * 32 + j)
    indices.append(-1)
```

I could make a PR to implement this feature.

Do we need support for this in Pyrr?

**Comment by Korijn** [comment]
You could reconstruct a `TRIANGLES` style index with some vectorized numpy code and reuse the `generate_vertex_normals` function as-is.

**Comment by cprogrammer1994** [comment]
Thanks!

Can you please check #66 if the solution is efficient? Is there a better way to do this using numpy?

**Comment by Korijn** [comment]
* Adding a unit test would definitely help understanding your scenario.
* Is `-1` your primitive restart index value?

I think this should work:

```python
zipped = np.array([indices[:-2], indices[1:-1], indices[2:]])
modified_index = zipped[:, ~np.any(zipped == -1, axis=0)].T
```

**Comment by cprogrammer1994** [comment]
Thanks!

The primitive restart index will be a parameter. But the default will be `-1`.

**Comment by Korijn** [comment]
The numpy version should be faster, particularly for very large indices.
