### ISSUE TITLE
pitch, roll, yaw used in different orders

### ISSUE THREAD

**Issue by ubald** [adamlwgriffiths/Pyrr#68]
In Quaternion and Euler/Vector3 the x, y, z values are used withe different meaning. 

In euler.py, lines 16, 19, 22: 
roll, pitch, yaw

In quaternion.py, create_from_eulers:
Doc says yaw, pitch, roll
Code uses pitch, yaw, roll

In quaternion.py, create_from_inverse_of_eulers:
Using getters from euler, so in the same order as euler

**Comment by Korijn** [comment]
I recommend setting up a PR to correct the issue. Perhaps you want to make the order configurable?

**Comment by ubald** [comment]
I don't mind fixing it, I just don't know what order should be used. I think the standard is roll, pitch, yaw, as in euler.py.
