### ISSUE TITLE
question: matrix33.create_from_quaternion needs to be transposed?

### ISSUE THREAD

**Issue by ando-takahiro** [adamlwgriffiths/Pyrr#70]
Thanks for making such nice software.  Let me ask you a question.

Now, I'm switching from our existing math library to Pyrr.  But the conversion function from quaternion to matrix seems wired...

I transposed this matrix, then Pyrr returns the same result with our existing library.

https://github.com/adamlwgriffiths/Pyrr/blob/master/pyrr/matrix33.py#L147-L149

I saw the link in the function, and I realized that Pyrr's current order is same with the link.
http://www.euclideanspace.com/maths/geometry/rotations/conversions/quaternionToMatrix/index.htm

As far as I understand, Pyrr is OpenGL order, right-handed coordinate, right?  So we should transpose because OpenGL order is transposed right-handed order.

**Comment by adamlwgriffiths** [comment]
Pyrr is in native OpenGL format. You can transpose to get the opposite using the .T function.

**Comment by ando-takahiro** [comment]
Thanks for your clarification.  So in that case, this code...

https://github.com/adamlwgriffiths/Pyrr/blob/master/pyrr/matrix33.py#L147-L149
```
    return np.array([
        [m00, m01, m02],
        [m10, m11, m12],
        [m20, m21, m22],
    ], dtype=dtype)
```

should be below, right?  Because OpenGL format is transposed.

```
    return np.array([
        [m00, m10, m20],
        [m01, m11, m21],
        [m02, m12, m22],
    ], dtype=dtype)
```

If I'd like to use matrix33, `.T` would work.  However, if I'd like to use `matrix.create_from_quaternion`, we need to transpose only 3x3 parts inside of matrix44. In my working environment, transposed one(the second one) worked correctly.

Thanks,

**Comment by adamlwgriffiths** [comment]
I'm confused. Are you saying the Pyrr maths is incorrect? Or are you just asking about its usage?

**Comment by ando-takahiro** [comment]
Sorry, but I think `create_from_quaternion` would be incorrect if pyrr is OpenGL format.  I wanted to ask you before saying this is not correct.

**Comment by adamlwgriffiths** [comment]
Sorry, I'm not entirely sure what you're suggesting.
If you can provide some code that demonstrates that this is an issue, I'm all ears.

**Comment by ando-takahiro** [comment]
Thanks, I'll try it :smile_cat:
