### ISSUE TITLE
Python 2.6 Builds Failing

### ISSUE THREAD

**Issue by foohyfooh** [adamlwgriffiths/Pyrr#75]
Since multipledispatch updated its version from 0.5.0 to 0.6.0 about 4 days ago, Python 2.6 builds stopped working. The multipledispatch library is now using collections.OrderedDict which was added in Python 2.7

Proposed Solutions:
- Drop Python 2.6 support
- Add multipledispatch==0.5.0 instead of using the latest version in requirements.txt and setup.py

**Comment by adamlwgriffiths** [comment]
Happy to drop 2.6.

**Comment by adamlwgriffiths** [comment]
I've added you as a collaborator, so feel free to fix and merge.
Appreciate the PRs you've done =)
