### ISSUE TITLE
question regarding Matrix.from_translation 

### ISSUE THREAD

**Issue by yscoffee** [adamlwgriffiths/Pyrr#85]
Hi

I am confusing about the print output of a Matrix44 object. 

By running Matrix44.from_translation, it looks the string visualization is not correct 
```
    x = pyrr.Matrix44.from_translation( [0,10,0])
    print( x )
````
output:
````
[[ 1  0  0  0]
 [ 0  1  0  0]
 [ 0  0  1  0]
 [ 0 10  0  1]]
````
I was expected it looks like:
````
[[ 1  0  0  0]
 [ 0  1  0  10]
 [ 0  0  1  0]
 [ 0  0  0  1]]
````

**Comment by adamlwgriffiths** [comment]
The library utilises the OpenGL layout for matrices.
https://en.wikipedia.org/wiki/Row-_and_column-major_order#Programming_languages_and_libraries
