### ISSUE TITLE
documentation quaternion has advertisement link

### ISSUE THREAD

**Issue by hnsz** [adamlwgriffiths/Pyrr#86]
The link titled  OpenGL:Tutorials:Using_Quaternions_to_represent_rotation

**Comment by adamlwgriffiths** [comment]
The change has propagated through and the link is no longer visible.

**Comment by adamlwgriffiths** [comment]
Ok, I've deleted 'stable' as a documentation target. I couldn't find a way to change what commit it looked at.
So the link is now gone from all readthedocs pages.
I've also added 0.10.1 as a version that is registered so we can have historic versions going forward.

Thanks again!

**Comment by hnsz** [comment]
Gladly
