### ISSUE TITLE
Inconsitent Position / Distance to plane

### ISSUE THREAD

**Issue by refelix** [adamlwgriffiths/Pyrr#87]
Thank you for this useful Library.
There is some unexpected behavior for planes concerning the sign of the distance:
Take for example the following Plane:
```
plane = pyrr.plane.create_from_position(position=[0, 0, 1], normal=[0, 0, 1])
```
which returns the expected plane: `array([ 0,  0,  1, -1])`. However `pyrr.plane.position(plane)` returns `array([ 0,  0, -1])`, instead of `[0, 0, 1]`
 A related issue can be observed when calculating the distance of a point calculated to lie on the plane, which should therefore be 0:
```pyrr.geometric_tests.point_height_above_plane(pyrr.geometric_tests.point_closest_point_on_plane([0, 0, 1], plane), plane)```
but returns -2

**Comment by adamlwgriffiths** [comment]
Ok, so looks like create from position should be:

    dtype = dtype or position.dtype
    # d = a * x  + b * y + c * z
    n = vector.normalize(normal)
    d = np.sum(n * position)
    return create(n, d, dtype)

point_height_above_plane looks like its giving an incorrect result.
It has mistakenly left out the division of the square root of the square of the point.
But there is still something NQR in there.

**Comment by adamlwgriffiths** [comment]
Because we keep normalised normal, it seems we can do vector.dot(normal, plane.position - point)

**Comment by adamlwgriffiths** [comment]
If you can take a look at https://github.com/adamlwgriffiths/Pyrr/pull/88 and see if that corrects your issues.
I'd also appreciate another set of eyes checking the maths over.
