### ISSUE TITLE
Unit tests not included in PyPI source distribution

### ISSUE THREAD

**Issue by c0deaddict** [adamlwgriffiths/Pyrr#90]
Unit tests are missing from the latest PyPI source distribution of Pyrr (https://files.pythonhosted.org/packages/aa/9a/43b75e07c3aa0c02f9360ad16b62a67fac855c355643ed3061538ee49fd3/pyrr-0.10.1.tar.gz).

I'm trying to get Pyrr working on NixOS, and by default NixOS tries to run the package's tests. Since they are missing this step fails.

**Comment by adamlwgriffiths** [comment]
I'm not aware of any python packages ever distributing the test code.

**Comment by adamlwgriffiths** [comment]
Looking at software like flask, there is a /tests directory in the source tar.gz.
Their setup.py does not mention the tests directory, so I'm not sure what they've done to include those in the source package.

**Comment by c0deaddict** [comment]
What i've seen in several python libraries is that there is a /tests/runtests.py file that is excluded from the Pypi source distribution and that the actual tests themselves are intertwined in the source code folders.

Flask does it differently indeed. I'm also not sure how they do it. It's not a major problem that the tests are missing, in NixOS it's also possible to build the package from the sources on Github.

Thanks for your time!

**Comment by adamlwgriffiths** [comment]
I would like to be in-keeping with Python packaging standards. If I get time I'll take a look.
If you solve this one before me please feel free to do a PR.

**Comment by adamlwgriffiths** [comment]
Ok, I've merged your code, bumped the version to 0.10.2, and uploaded the tar.gz and wheel distributions.
Let me know if this fixes your problem.

**Comment by c0deaddict** [comment]
Thanks! It does, the Nix derivation [now builds](https://github.com/NixOS/nixpkgs/pull/57661)!

**Comment by adamlwgriffiths** [comment]
Sweet!
