### ISSUE TITLE
Quaternion -> Euler

### ISSUE THREAD

**Issue by alanjfs** [adamlwgriffiths/Pyrr#95]
Hi @adamlwgriffiths, apologies if this is obvious to a math-able person, but I can get an Quaternion from an Euler, but can't seem to figure out how to go the other way around?

```python
import pyrr
euler = pyrr.Vector3([1, 0, 0])
quat = pyrr.quaternion.from_eulers(euler)
euler = pyrr.__?__(quat)
```

I've tried going through matrices but they also don't seem to be able to hand out eulers, only quaternion via it's `.decompose()` method.

**Comment by adamlwgriffiths** [comment]
Sorry for the delay.
In general, you should just use Quaternions. As I didn't have any need for eulers there isn't an equivalent function.
Feel free to implement one and do a PR =)

**Comment by alanjfs** [comment]
Thanks for the reply, for some reason I didn't get a notification so I'm also sorry for the delay! :)

That makes sense, however for completeness I'll include my usecase too.

1. Take the mouse XY position
2. Append to an existing Vector3 (representing rotation)
3. Translate it into a matrix (using Matrix44.from_eulers)
4. Apply as a "camera transform"
5. Now store the resulting rotation as a starting point for next mouse/camera interaction

It's (5) where I'd like to somehow get the Euler rotation back from a matrix (or quaternion, given I can also get a quaternion from a matrix).

I lack enough understanding in maths and quaternions to make a PR, but if anything comes up I'll see what I can do. For the time being, I've resorted to both applying and storing the rotations separately, to avoid having to convert from matrix to Euler; however it is quite limiting.

**Comment by adamlwgriffiths** [comment]
You can store a Quaternion or Matrix. Quaternions are generally preferable.
To update:
1. create a new quaterion / matrix using the mouse position. Simplest way to explain how to do this is to make 2 rotations (one for x, one for y) and multiply them to create a new rotation. Ie, create_from_x_rotation, create_from_y_rotation, with the value as the amount.
2. multiply the stored value by the newly created value.

There's an old example [here](https://github.com/adamlwgriffiths/PyGLy/blob/master/pygly/transform.py#L153) which will be incredibly broken (the maths was wrong).
But it demonstrates the kind of concept.

You just need to break the rotations/translations down into steps, then accumulate them. A good example is how a scene graph works (whether they are a good idea is debatable).

**Comment by alanjfs** [comment]
Bah, still no notifications. Thought I fixed that, sorry again for the delay!

Thanks for this, reading it out loud makes sense to me. I'll experiment with this some more. For the time being, I'm happy to consider this issue resolved. Thanks again!
