### ISSUE TITLE
Quaternions working?

### ISSUE THREAD

**Issue by pbridger** [adamlwgriffiths/Pyrr#96]
Perhaps I am missing something, but this doesn't seem right:

```
>>> Matrix33.from_y_rotation(pi/2) * Vector3([0, 0, 1])
Vector3([-1.000000e+00,  0.000000e+00,  6.123234e-17]) # good

>>> Quaternion.from_y_rotation(pi/2) * Vector3([0, 0, 1])
Vector3([0., 0., 0.]) # not good

>>> Quaternion.from_matrix(Matrix33.from_y_rotation(pi/2)) * Vector3([0, 0, 1])
Vector3([0., 0., 0.]) # also suboptimal
```

Generally, it's a very nice library so thanks for your work!

**Comment by adamlwgriffiths** [comment]
integer != float

>>> from pyrr import *
>>> from math import pi
>>> Quaternion.from_matrix(Matrix33.from_y_rotation(pi/2)) * Vector3([0., 0., 1.])
Vector3([1.00000000e+00, 0.00000000e+00, 2.22044605e-16])
