### ISSUE TITLE
ray_intersect_aabb nan issue

### ISSUE THREAD

**Issue by XHwind** [adamlwgriffiths/Pyrr#99]
Error message

> line 87, in ray_intersect_aabb
>     t = min(x for x in [tmin, tmax] if x >= 0)
> ValueError: min() arg is an empty sequence

The function `ray_intersect_aabb` will have nan when trying to execute `t = min(x for x in [tmin, tmax] if x >= 0)`. This because when calculating `t1 = (aabb[0,0] - ray[0,0]) * dir_fraction[ 0 ]`, if ` (aabb[0,0] - ray[0,0])=0` and `dir_fraction[ 0 ]=np.inf`, then t1 will become nan. It would be great if it can be solved. Thank you~
Example 
```
ray=np.array([[2.5, 4. , 0.5],[0. , 0. , 1. ]])
aabb=np.array([[2.5, 0. , 4.8], [5. , 5. , 5. ]])
```

**Comment by philRudd69** [comment]
I encountered the same problem too e.g. for the following combination:
```
voxel:  [[0 0 0] [1 1 1]]
ray: [[0.  0.  1.43]  [0.  0.7192546  0.69474659]]
```
